In [1]:
print("shgkjha")

shgkjha

In [2]:
import numpy as np 
import pandas as pd

In [4]:
data=pd.read_csv(r"C:\Users\athar\Desktop\Inprocesss\DS\ml1\notebooks\data\gemstone.csv")

In [5]:
data

,id,carat,cut,color,clarity,depth,table,x,y,z,price
0,0,1.52,Premium,F,VS2,62.2,58.0,7.27,7.33,4.55,13619
1,1,2.03,Very Good,J,SI2,62.0,58.0,8.06,8.12,5.05,13387
2,2,0.70,Ideal,G,VS1,61.2,57.0,5.69,5.73,3.50,2772
3,3,0.32,Ideal,G,VS1,61.6,56.0,4.38,4.41,2.71,666
4,4,1.70,Premium,G,VS2,62.6,59.0,7.65,7.61,4.77,14453
...,...,...,...,...,...,...,...,...,...,...,...
193568,193568,0.31,Ideal,D,VVS2,61.1,56.0,4.35,4.39,2.67,1130
193569,193569,0.70,Premium,G,VVS2,60.3,58.0,5.75,5.77,3.47,2874
193570,193570,0.73,Very Good,F,SI1,63.1,57.0,5.72,5.75,3.62,3036
193571,193571,0.34,Very Good,D,SI1,62.9,55.0,4.45,4.49,2.81,681
193572,193572,0.71,Good,E,SI2,60.8,64.0,5.73,5.71,3.48,2258

In [6]:
X=data.drop(labels=["price"],axis=1)

In [7]:
Y=data[["price"]]

In [8]:
X

            id  carat        cut color clarity  depth  table     x     y     z
0            0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1            1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2            2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3            3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4            4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...        ...    ...        ...   ...     ...    ...    ...   ...   ...   ...
193568  193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569  193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570  193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571  193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572  193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 10 columns]

In [9]:
Y

        price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [10]:
categorical_cols=X.select_dtypes(include='object').columns
numerical_cols=X.select_dtypes(exclude='object').columns

In [11]:
categorical_cols

Index(['cut', 'color', 'clarity'], dtype='object')

In [12]:
numerical_cols

Index(['id', 'carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [13]:
X.select_dtypes(include='object')

              cut color clarity
0         Premium     F     VS2
1       Very Good     J     SI2
2           Ideal     G     VS1
3           Ideal     G     VS1
4         Premium     G     VS2
...           ...   ...     ...
193568      Ideal     D    VVS2
193569    Premium     G    VVS2
193570  Very Good     F     SI1
193571  Very Good     D     SI1
193572       Good     E     SI2

[193573 rows x 3 columns]

In [14]:
#Define the custom ranking for each ordinal variable
cut_cat=['Fair','Good','Very Good','Premium','Ideal']
color_cat=['D','E','F','G','H','I','J']
clarity_cat=['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [15]:
from sklearn.impute import SimpleImputer         #######  For handling missing values
from sklearn.preprocessing import StandardScaler #######  For handling feature scaling (i.e. to bring data in specific range)
from sklearn.preprocessing import OrdinalEncoder #######  For ordinal encoding

###Piplines

from sklearn.pipeline  import  Pipeline
from sklearn.compose import ColumnTransformer

In [16]:
num_pipeline=Pipeline(

    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('scaler',StandardScaler())
    ]
)

In [17]:
cat_pipeline=Pipeline( 

    steps=[

        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('scaler',OrdinalEncoder(categories=[cut_cat,color_cat,clarity_cat]))
        ]
)

In [18]:
preprocesor=ColumnTransformer(
    [
        ('num_pipeline',num_pipeline,numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
    ]
)

In [19]:
#Train test split

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=30)

In [21]:
preprocesor.fit_transform(X_train)

array([[-1.12891398,  0.4737665 ,  3.22017586, ...,  0.        ,
         2.        ,  3.        ],
       [ 1.66215812, -0.84569736,  0.07580627, ...,  4.        ,
         3.        ,  2.        ],
       [-1.41593138,  0.73333317, -0.20163811, ...,  2.        ,
         4.        ,  2.        ],
       ...,
       [ 0.03482578,  0.45213595,  1.55550961, ...,  1.        ,
         3.        ,  2.        ],
       [-0.87316528,  0.6684415 , -1.7738229 , ...,  4.        ,
         3.        ,  4.        ],
       [ 1.30419581,  0.25746095,  0.81565794, ...,  4.        ,
         3.        ,  2.        ]])

In [22]:
preprocesor.transform(X_test)

array([[-0.47270042, -0.56450014, -0.94148977, ...,  3.        ,
         1.        ,  3.        ],
       [-0.57274955, -0.17515015,  1.00062086, ...,  2.        ,
         4.        ,  2.        ],
       [ 1.5823764 , -1.06200291,  0.26076919, ...,  4.        ,
         4.        ,  7.        ],
       ...,
       [-0.66013379,  1.53366371,  0.35325065, ...,  2.        ,
         3.        ,  4.        ],
       [ 0.27168445,  1.62018593,  0.07580627, ...,  3.        ,
         1.        ,  3.        ],
       [-0.08795936, -0.97548069,  0.16828773, ...,  2.        ,
         5.        ,  4.        ]])

In [23]:
preprocesor.get_feature_names_out()

array(['num_pipeline__id', 'num_pipeline__carat', 'num_pipeline__depth',
       'num_pipeline__table', 'num_pipeline__x', 'num_pipeline__y',
       'num_pipeline__z', 'cat_pipeline__cut', 'cat_pipeline__color',
       'cat_pipeline__clarity'], dtype=object)

In [24]:
X_train=pd.DataFrame(preprocesor.fit_transform(X_train),columns=preprocesor.get_feature_names_out())
X_test=pd.DataFrame(preprocesor.transform(X_test),columns=preprocesor.get_feature_names_out())

In [25]:
X_train

,num_pipeline__id,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-1.128914,0.473767,3.220176,-0.641637,0.445161,0.398319,0.747248,0.0,2.0,3.0
1,1.662158,-0.845697,0.075806,-0.120391,-0.880410,-0.854100,-0.862659,4.0,3.0,2.0
2,-1.415931,0.733333,-0.201638,0.922103,0.823895,0.897472,0.848774,2.0,4.0,2.0
3,0.978218,-0.196781,0.260769,-0.641637,-0.050801,-0.010079,-0.006943,4.0,5.0,3.0
4,-1.664722,-0.542870,-0.571564,0.400856,-0.465605,-0.436627,-0.485564,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...
145174,-0.543842,-1.040372,-0.016675,-0.641637,-1.268162,-1.244347,-1.239754,4.0,1.0,2.0
145175,-0.905811,0.992900,0.168288,-0.641637,1.049332,1.115284,1.080832,4.0,3.0,1.0
145176,0.034826,0.452136,1.555510,-0.641637,0.517301,0.588905,0.703737,1.0,3.0,2.0
145177,-0.873165,0.668442,-1.773823,1.443349,0.868983,0.951925,0.689233,4.0,3.0,4.0
145178,1.304196,0.257461,0.815658,-0.120391,0.382038,0.416470,0.471678,4.0,3.0,2.0

In [26]:
X_test

,num_pipeline__id,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.472700,-0.564500,-0.941490,-0.641637,-0.429535,-0.463854,-0.500067,3.0,1.0,3.0
1,-0.572750,-0.175150,1.000621,-0.120391,-0.041783,-0.028230,0.036568,2.0,4.0,2.0
2,1.582376,-1.062003,0.260769,-0.120391,-1.304232,-1.298800,-1.268762,4.0,4.0,7.0
3,-0.218222,0.971269,-0.201638,1.964596,1.049332,0.997302,0.979307,3.0,3.0,3.0
4,-1.161023,-0.932220,-1.311416,0.400856,-1.006654,-0.990233,-1.065710,3.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...
48389,1.541037,-0.499608,0.445732,-0.641637,-0.402483,-0.373099,-0.355031,4.0,1.0,4.0
48390,1.201052,-0.175150,0.075806,0.922103,-0.014731,-0.019154,-0.006943,3.0,4.0,1.0
48391,-0.660134,1.533664,0.353251,0.400856,1.464137,1.432926,1.457928,2.0,3.0,4.0
48392,0.271684,1.620186,0.075806,0.922103,1.572347,1.550908,1.559453,3.0,1.0,3.0
48393,-0.087959,-0.975481,0.168288,1.443349,-1.150934,-1.126365,-1.123725,2.0,5.0,4.0

In [27]:
### Applying Lasso,Ridge,Elastic net regression

In [28]:
from  sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
import numpy as np
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rsme=np.sqrt(mean_squared_error(true,predicted))
    r2_square=r2_score(true,predicted)
    return mae,rsme,r2_square

In [29]:
models={
       'LinearRegression':LinearRegression(),
       'Lasso':Lasso(),
       'Ridge':Ridge(),
       'ElasticNet':ElasticNet()
       }

In [30]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [31]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'ElasticNet']

In [32]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(models)

{'LinearRegression': LinearRegression(), 'Lasso': Lasso(), 'Ridge': Ridge(), 'ElasticNet': ElasticNet()}
{'LinearRegression': LinearRegression(), 'Lasso': Lasso(), 'Ridge': Ridge(), 'ElasticNet': ElasticNet()}
{'LinearRegression': LinearRegression(), 'Lasso': Lasso(), 'Ridge': Ridge(), 'ElasticNet': ElasticNet()}
{'LinearRegression': LinearRegression(), 'Lasso': Lasso(), 'Ridge': Ridge(), 'ElasticNet': ElasticNet()}

In [33]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'ElasticNet'])

In [34]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet()])

In [35]:

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,Y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    #this is a validation(test) score
    mae, rmse, r2_square=evaluate_model(Y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 1020.9110725889525
MAE: 677.5633396791611
R2 score 93.63481854226411
===================================


Lasso
Model Training Performance
RMSE: 1020.8737430356548
MAE: 678.7748068943138
R2 score 93.63528401872485
===================================


Ridge
Model Training Performance
RMSE: 1020.9108217471854
MAE: 677.5913282939166
R2 score 93.63482167016274
===================================


ElasticNet
Model Training Performance
RMSE: 1520.4400619026928
MAE: 1052.7675047681414
R2 score 85.88198726620556
===================================

In [36]:
trained_model_list

[]

In [37]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'ElasticNet']

In [38]:
r2_list

[0.9363481854226412,
 0.9363528401872484,
 0.9363482167016274,
 0.8588198726620556]